name: Backend API Integration Pipeline

on:
  push:
    paths: ["sandbox/**"]
    branches: [master]
  pull_request:
    paths: ["sandbox/**"]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - uses: actions/checkout@v2
      - name: Install data processing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pylint
          pip install nbqa
          pip install -r medical_segmentation/requirements.txt
      - name: Pylint
        run: |
          pylint medical_segmentation
          nbqa pylint medical_segmentation/*.ipynb --disable=C0114
