name: Backend API Integration Pipeline

on:
  push:
    paths: ["sandbox/**"]
    branches: [master]
  pull_request:
    paths: ["sandbox/**"]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - uses: actions/checkout@v2
      - name: Install data processing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pylint
          pip install nbqa
      - name: Install sandbox dependencies
        run: |
          if [ -f sandbox/requirements.txt ]; then pip install -r sandbox/requirements.txt; fi
      - name: Pylint
        run: |
          pylint sandbox --rcfile=.pylintrc --init-hook='import sys; sys.path.append("sandbox/")'
          nbqa pylint my_notebook.ipynb --disable=C0114
